### ISSUE TITLE
not all the gists are displayed (pagination)

### ISSUE THREAD

**Issue by brpaz** [dbankier/vscode-gist#10]
Hello. 
I noticed that not all my gists appear on the menu  Since GitHub API limits the number results by default, and after looking at the code, I think its only returning the first page.
This is a big limitation for those who have many gists.

A possible solution would be to iterate over each page but I am afraid that would make the extension slower.

Any ideas?

**Comment by kenhowardpdx** [comment]
closing in favor of https://github.com/kenhowardpdx/vscode-gist/issues/1
