### ISSUE TITLE
"create new PRIVATE gist" creates anonymous gist after showing error message

### ISSUE THREAD

**Issue by sekogan** [dbankier/vscode-gist#14]
Repro steps:

- install the extension from VSC, reload VSC,
- run the command "Gist: create new PRIVATE gist",
- enter some name to the "Enter the gist description" box and press Enter,
- an error message "Sorry, git must be installed." is displayed. Press the "Close" button.
- a browser window is opened with a new **anonymous** gist. **The gist contains the text from the currently opened (in VSC) file.**

What is wrong here:
- First of all the gist should not be anonymous (or it should be mentioned in the command name that it will be anonymous).
- It should not create a gist at all if an error occurred.
- It should check system requirements (like presence of git) before doing anything.
- These requirements should be mentioned in the installation instructions.
- It should be mentioned in the command name that the gist will be created from the text in the current window. Because otherwise it is too easy to blindly create anonymous gist with sensitive and private information that could be accidentally opened in VSC (as it was in my case). It's worth noting that anonymous gists cannot be deleted or edited which makes the overall user experience truly breathtaking.

Extension version 0.5.2, VSC version 1.8.1, Windows 10 RS1 x64.

**Comment by sekogan** [comment]
I must clarify the last point. This whole mess happened because I expected that the "Gist: create new PRIVATE gist" will create a new document and will allow me to edit and save it. Because that's what the "New File" command does. The real action was more like "create anonymous gist from the current file" or "publish current file as anonymous gist".

**Comment by dbankier** [comment]
Private gists should create "Secret" gists from you current file.
The way it works off the current file is in the README.md. 
The fact that on a failure it created an anonymous one Is a bug. 
I don't have time to look into it at the moment.

**Comment by kenhowardpdx** [comment]
closing in favor of https://github.com/kenhowardpdx/vscode-gist/issues/3
