### ISSUE TITLE
Store Auth Token outside of user settings?

### ISSUE THREAD

**Issue by ghost** [dbankier/vscode-gist#15]
I use the extension [Settings Sync](https://github.com/shanalikhan/code-settings-sync) which stores my user settings in a Gist.  I've decided to make mine public as there is no sensitive information contained within.

This means I don't want to put a Github token in my settings.  I could go ahead and make them private again and then use this extension, but I'd like to avoid that if possible, and I don't see authentication as part of settings anyway.

Since Settings Sync also interacts with Gists, and does not save the token in user settings, perhaps their repository could offer some guidance?

**Comment by kenhowardpdx** [comment]
Thanks for the suggestion. I'll let you know if this gets implemented.

**Comment by ghost** [comment]
Thanks, I'd appreciate it.

I looked around a bit in their repo but I didn't see anything in particular that I could point to and say "doing something like this would let you store and later retrieve the key".  Perhaps someone with more experience in Typescript + VS Code extension authoring would have an easier time.

**Comment by kenhowardpdx** [comment]
This is implemented in https://github.com/dbankier/vscode-gist/commit/62cb880372ecd6b4a04cb70bf03ef777feab9dc3 currently in master. I'll update here when it's published to the Marketplace.

**Comment by ghost** [comment]
Thanks, much appreciated!
