### ISSUE TITLE
Authentication doesn't support 2FA

### ISSUE THREAD

**Issue by jcam3ron** [dbankier/vscode-gist#26]
Hi, I have 2FA enabled on my Github account and cannot login with this plugin as it doesn't seem to support it.

See https://developer.github.com/v3/auth/#working-with-two-factor-authentication for details

**Comment by kenhowardpdx** [comment]
@jcam3ron thank you. I hope to add support for 2FA in the future.

**Comment by kenhowardpdx** [comment]
closing in favor of https://github.com/kenhowardpdx/vscode-gist/issues/6
