### ISSUE TITLE
Cannot read property 'label' of null

### ISSUE THREAD

**Issue by resting** [dbankier/vscode-gist#27]
I get the above error message when I tried opening personal or starred gist.
VSCode: Version 1.13.0 (1.13.0)
GE: v0.5.3

**Comment by AndrewHuffman** [comment]
@kenhowardpdx in #16 states this was fixed in `master` but has that made it out to the marketplace?

**Comment by kenhowardpdx** [comment]
@andrewhuffman it has not. I'll update you when it has been published.

**Comment by dbankier** [comment]
Sorry. I'll push an update tomorrow. Ken, We should look at transfering
everything across to you. If we can't transfer the marketplace plugin we
should look at deprecating mine and starting a new one.

**Comment by kenhowardpdx** [comment]
@dbankier I agree. We can chat through email or skype anytime.

**Comment by dbankier** [comment]
@kenhowardpdx, I can't do a release. `tsc` is failing based on the current dependencies. Type errors.

**Comment by kenhowardpdx** [comment]
@dbankier I'll check it out. It likely needs a fresh `npm install` on your side.

**Comment by kenhowardpdx** [comment]
@dbankier be sure to run `npm install` and `npm run vscode:prepublish`. Your version of TypeScript might be outdated so running the prepublish script uses the project's copy of tsc.

**Comment by kenhowardpdx** [comment]
Closing in favor of https://github.com/kenhowardpdx/vscode-gist/issues/7
