### ISSUE TITLE
command 'workbench.action.focusLeftEditor' not found

### ISSUE THREAD

**Issue by flipphillips** [dbankier/vscode-gist#29]
Was trying to open multi-file gist of mine (at https://gist.github.com/flipphillips/336908841dc73d33c248eb4687c1cac2 ) and I'm being told `command 'workbench.action.focusLeftEditor' not found` and no gist appears.

**Comment by kenhowardpdx** [comment]
@flipphillips thanks for the bug report. I'll look into this.

**Comment by kenhowardpdx** [comment]
Closing in favor of https://github.com/kenhowardpdx/vscode-gist/issues/8
