### ISSUE TITLE
PRIVATE gist is public

### ISSUE THREAD

**Issue by teddybradford** [dbankier/vscode-gist#4]
When I use "create new PRIVATE gist" from the command palette, it creates a public gist instead of a secret one.

**Comment by dbankier** [comment]
odd... what os?

**Comment by teddybradford** [comment]
I'm using OS X 10.11.4

**Comment by satokaz** [comment]
I also had the same problem.

Mac OS X 10.11.4
VScode 1.1.0-insider 

It seems `type! == Exports.PRIVATE` is not be evaluated correctly.
Effective interim fix the following:

``` diff
diff --git a/src/api/gist.ts b/src/api/gist.ts
index f5b683e..4cdd9ae 100644
--- a/src/api/gist.ts
+++ b/src/api/gist.ts
@@ -41,7 +41,7 @@ export = {
   create: (type: Type, description: string, file_name: string, text_content: string) => {
     var body = {
       description: description,
-      public: type !== exports.PRIVATE,
+      public: type !== Type.PRIVATE,
       files: {}
     }
     body.files[file_name] = {
```

or Applied to the installed extension:

Modify the gist.js.
and Restart the vscode.

``` diff
--- .vscode-insiders/extensions/dbankier.vscode-gist-0.5.0/out/api/gist.js.orig 2016-05-13 09:42:04.000000000 +0900
+++ .vscode-insiders/extensions/dbankier.vscode-gist-0.5.0/out/api/gist.js  2016-05-13 09:42:19.000000000 +0900
@@ -38,7 +38,7 @@
     create: function (type, description, file_name, text_content) {
         var body = {
             description: description,
-            public: type !== exports.PRIVATE,
+            public: type !== Type.PRIVATE,
             files: {}
         };
         body.files[file_name] = {
```

I can not determine the validity of this fix...

**Comment by dbankier** [comment]
@satokaz, thanks for the fix. 
(was working previously... perhaps a new ts or vscode version broke it.)

pushing out an update now.

**Comment by satokaz** [comment]
@dbankier, Thank you immediately fix!
I was confirmed the behavior was expected in the update of v0.5.1.

and, 

repository URL link in the marketplace is incorrect.

https://marketplace.visualstudio.com/items?itemName=dbankier.vscode-gist
Link of the Started is https://github.com/ziyasal/vscode-gist. 

Correctly, https://github.com/dbankier/vscode-gist/

Thanks!

**Comment by dbankier** [comment]
Thanks - fixed.
