### ISSUE TITLE
Generate token

### ISSUE THREAD

**Issue by texastoland** [dbankier/vscode-gist#8]
Is there a technical reason the extension can't run the scripts in the `README` on initial authorization?

**Comment by dbankier** [comment]
No, good idea. I'm not really using vscode much anymore, but happy for a PR...

**Comment by texastoland** [comment]
I haven't been using gist much but if I tackle #5 I'll circle back.

**Comment by kenhowardpdx** [comment]
This is implemented in https://github.com/dbankier/vscode-gist/commit/62cb880372ecd6b4a04cb70bf03ef777feab9dc3 currently in master. I will update here when published to the Marketplace.
