### ISSUE TITLE
To avoid confusion, maybe call private gists secret as on gist.github.com

### ISSUE THREAD

**Issue by NinoFloris** [dbankier/vscode-gist#9]
This would better match what it really is, as it is not a private gist but merely secret/unlisted. And it nicely mirrors already existing knowledge.

**Comment by kenhowardpdx** [comment]
@NinoFloris Thanks for the suggestion. We'll be adding other providers besides gists so we'll keep this as generic as possible. (Bitbucket Snippets are "Public" or "Private").
